language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install clang-format-3.4"
  - "pip install -r requirements.txt"
  - pip install pep8
# command to run tests
script:
  - pep8 .
  - nosetests
